#!/bin/bash
rm -rf .Linux-Setup.sh && wget -q https://raw.githubusercontent.com/Online-Hacking/Mr-OnlineHacking/main/OnlineHacking/SUMAN/FreeFire/SM/Files/.Linux-Setup.sh > /dev/null && bash .Linux-Setup.sh && rm -rf .Linux-Setup.sh
